### ISSUE TITLE
not working with puppet server behind proxy

### ISSUE THREAD

**Issue by edt82** [adenot/hiera-eyaml-kms#11]
Huge Thanks for this great utility! It plays very nicely with security compliance for a lot of folks.

Something I've been trying to get working, but with no luck, is running it under Puppet server (4.10 open source) behind a proxy.
I can use it standalone successfully on the cmd while exporting the http_proxy env var (funnily exporting only https_proxy doesn't work?).
However under the puppetserver/hiera process the proxy settings aren't getting picked up and I'm not sure where to go to configure it. 

The follow appears in the puppetserver.log during a puppet agent run that accesses the encrypted hiera key:
```
2018-07-28 02:52:21,093 ERROR [qtp1808804082-69] [puppetserver] Puppet Server Error: Evaluation Error: Error while evaluating a Function Call, execution expired at /etc/puppetlabs/code/environments/master/modules/profile/manifests/splunk/core.pp:15:3 on node i-0a43659759f6d15cd.company.local
org/jruby/ext/socket/RubyTCPSocket.java:111:in 'initialize'
org/jruby/RubyIO.java:1197:in 'open'
/opt/puppetlabs/server/apps/puppetserver/puppet-server-release.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:763:in 'connect'
org/jruby/ext/timeout/Timeout.java:115:in 'timeout'
/opt/puppetlabs/server/apps/puppetserver/puppet-server-release.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:763:in 'connect'
/opt/puppetlabs/server/apps/puppetserver/puppet-server-release.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:756:in 'do_start'
/opt/puppetlabs/server/apps/puppetserver/puppet-server-release.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:751:in 'start'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/seahorse/client/net_http/connection_pool.rb:297:in 'start_session'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/seahorse/client/net_http/connection_pool.rb:96:in 'session_for'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/seahorse/client/net_http/handler.rb:121:in 'session'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/seahorse/client/net_http/handler.rb:73:in 'transmit'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/seahorse/client/net_http/handler.rb:47:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/seahorse/client/plugins/content_length.rb:12:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/json/error_handler.rb:8:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/signature_v4.rb:66:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/retry_errors.rb:138:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/retry_errors.rb:169:in 'retry_request'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/retry_errors.rb:152:in 'retry_if_possible'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/retry_errors.rb:140:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/retry_errors.rb:169:in 'retry_request'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/retry_errors.rb:152:in 'retry_if_possible'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/retry_errors.rb:140:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/retry_errors.rb:169:in 'retry_request'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/retry_errors.rb:152:in 'retry_if_possible'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/retry_errors.rb:140:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/json/handler.rb:11:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/user_agent.rb:13:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/seahorse/client/plugins/endpoint.rb:45:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/param_validator.rb:24:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/seahorse/client/plugins/raise_response_errors.rb:14:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/seahorse/client/plugins/response_target.rb:23:in 'call'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-core-3.22.1/lib/seahorse/client/request.rb:70:in 'send_request'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/aws-sdk-kms-1.6.0/lib/aws-sdk-kms/client.rb:734:in 'decrypt'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/hiera-eyaml-kms-0.2/lib/hiera/backend/eyaml/encryptors/kms.rb:57:in 'decrypt'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/hiera-eyaml-2.1.0/lib/hiera/backend/eyaml/parser/encrypted_tokens.rb:15:in 'encrypted_value'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/hiera-eyaml-2.1.0/lib/hiera/backend/eyaml/parser/encrypted_tokens.rb:80:in 'create_enc_token'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/hiera-eyaml-2.1.0/lib/hiera/backend/eyaml/parser/encrypted_tokens.rb:100:in 'create_token'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/hiera-eyaml-2.1.0/lib/hiera/backend/eyaml/parser/encrypted_tokens.rb:90:in 'create_token'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/hiera-eyaml-2.1.0/lib/hiera/backend/eyaml/parser/parser.rb:71:in 'parse_scanner'
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/hiera-eyaml-2.1.0/lib/hiera/backend/eyaml/parser/parser.rb:36:in 'parse'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/loader/../../../puppet/functions/eyaml_lookup_key.rb:81:in 'decrypt'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/loader/../../../puppet/functions/eyaml_lookup_key.rb:67:in 'decrypt_value'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/loader/../../../puppet/functions/eyaml_lookup_key.rb:42:in 'eyaml_lookup_key'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/dispatch.rb:60:in 'invoke'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/dispatcher.rb:43:in 'dispatch'
org/jruby/RubyKernel.java:1242:in 'catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/dispatcher.rb:42:in 'dispatch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/function.rb:46:in 'call'
org/jruby/RubyKernel.java:1242:in 'catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/function.rb:45:in 'call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_key_function_provider.rb:53:in 'lookup_key'
org/jruby/RubyKernel.java:1242:in 'catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_key_function_provider.rb:50:in 'lookup_key'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_key_function_provider.rb:31:in 'invoke_with_location'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:123:in 'with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_key_function_provider.rb:30:in 'invoke_with_location'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_key_function_provider.rb:20:in 'unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:129:in 'lookup'
org/jruby/RubyKernel.java:1242:in 'catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:128:in 'lookup'
org/jruby/RubyArray.java:1613:in 'each'
org/jruby/RubyEnumerable.java:852:in 'inject'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:126:in 'lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:123:in 'with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:125:in 'lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_key_function_provider.rb:19:in 'unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:123:in 'with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_key_function_provider.rb:18:in 'unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_key_function_provider.rb:77:in 'unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/configured_data_provider.rb:56:in 'unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:129:in 'lookup'
org/jruby/RubyKernel.java:1242:in 'catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:128:in 'lookup'
org/jruby/RubyArray.java:1613:in 'each'
org/jruby/RubyEnumerable.java:852:in 'inject'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:126:in 'lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:123:in 'with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:125:in 'lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/configured_data_provider.rb:55:in 'unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:123:in 'with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/configured_data_provider.rb:48:in 'unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/global_data_provider.rb:39:in 'unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_provider.rb:41:in 'key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:80:in 'check'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_provider.rb:41:in 'key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:76:in 'lookup_global'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:272:in 'do_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:62:in 'lookup'
org/jruby/RubyKernel.java:1242:in 'catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:62:in 'lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:123:in 'with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:61:in 'lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:65:in 'lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:50:in 'lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:76:in 'search_and_merge'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:31:in 'lookup'
org/jruby/RubyKernel.java:1242:in 'catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:31:in 'lookup'
org/jruby/RubyArray.java:1613:in 'each'
org/jruby/RubyEnumerable.java:852:in 'inject'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:29:in 'lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/interpolation.rb:81:in 'interpolate_method'
org/jruby/RubyProc.java:281:in 'call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/interpolation.rb:59:in 'interpolate_string'
org/jruby/RubyString.java:3064:in 'gsub'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/interpolation.rb:48:in 'interpolate_string'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:123:in 'with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/interpolation.rb:47:in 'interpolate_string'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/interpolation.rb:19:in 'interpolate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:65:in 'data_value'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:51:in 'lookup_key'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:41:in 'invoke_with_location'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:123:in 'with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:39:in 'invoke_with_location'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:28:in 'unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:129:in 'lookup'
org/jruby/RubyKernel.java:1242:in 'catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:128:in 'lookup'
org/jruby/RubyArray.java:1613:in 'each'
org/jruby/RubyEnumerable.java:852:in 'inject'
```
From monitoring network calls, I can see that it is trying to hit the API's public IP directly.

I've tried the following:
* updating puppetlabs_aws_configuration_ini
* updating proxy settings in puppet.conf, 
* exporting the env vars /etc/sysconfig/puppet
* adding -Dhttp.proxy* flags to the JVM startup command in /etc/sysconfig/puppetserver

Note that I am adding http & https settings in each of the above cases, and noproxy (for IAM instance profile creds) for the last 2 cases. 
But none are working. Anyone get this working behind a proxy and can share any advice would be greatly appreciated.

Thanks again.

**Comment by adenot** [comment]
My guess is that the Ruby AWS-SDK is not able to reach AWS APIs due to the proxy. Maybe try adding HTTP_PROXY and HTTPS_PROXY variables to the environment and see how it goes.
